spring:
  profiles.active: test
---  
spring:
    profiles: test
    jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/book_db
        username: sumangal
        password: linux
server:
    port: 9005
